import { describe, expect, it } from 'vitest'
import {
  joinDescriptors,
  mergeDuplicateEntries,
  splitDescriptors
} from '../scripts/lockfile-entries.mjs'

const PREAMBLE = `# This file is generated by running "yarn install"\n__metadata:\n  version: 8`

const entry = (header: string, resolution: string, extra = '') =>
  `${header}:\n  version: 1.0.0\n  resolution: "${resolution}"${extra}\n  languageName: node\n  linkType: hard`

describe('lockfile entry merging', () => {
  it('merges entries that resolve to the same package', () => {
    const lockfile = [
      PREAMBLE,
      entry('"ms@npm:^2.1.1"', 'ms@npm:2.1.3'),
      entry('"ms@npm:^2.1.3"', 'ms@npm:2.1.3')
    ].join('\n\n')

    const merged = mergeDuplicateEntries(lockfile)
    expect(merged).toContain('"ms@npm:^2.1.1, ms@npm:^2.1.3":')
    // The duplicate body is gone, not merely re-headed.
    expect(merged.match(/resolution: "ms@npm:2\.1\.3"/g)).toHaveLength(1)
  })

  it('keeps entries for different versions apart', () => {
    const lockfile = [
      PREAMBLE,
      entry('"p-limit@npm:^2.2.0"', 'p-limit@npm:2.3.0'),
      entry('"p-limit@npm:^3.1.0"', 'p-limit@npm:3.1.0')
    ].join('\n\n')

    const merged = mergeDuplicateEntries(lockfile)
    expect(merged).toContain('"p-limit@npm:^2.2.0":')
    expect(merged).toContain('"p-limit@npm:^3.1.0":')
  })

  it('keeps entries whose bodies differ apart even at the same version', () => {
    const lockfile = [
      PREAMBLE,
      entry('"a@npm:^1.0.0"', 'a@npm:1.0.0', '\n  dependencies:\n    b: "npm:^1.0.0"'),
      entry('"a@npm:^1.0.1"', 'a@npm:1.0.0')
    ].join('\n\n')

    expect(mergeDuplicateEntries(lockfile)).not.toContain('"a@npm:^1.0.0, a@npm:^1.0.1":')
  })

  it('preserves a descriptor whose range ends in a space', () => {
    // A real range in this repo's lockfile is `^3.1.0 `. Trimming it silently
    // makes the package unresolvable.
    const header = '"p-limit@npm:^3.0.2, p-limit@npm:^3.1.0 "'
    expect(splitDescriptors(header)).toEqual(['p-limit@npm:^3.0.2', 'p-limit@npm:^3.1.0 '])

    const lockfile = [PREAMBLE, entry(header, 'p-limit@npm:3.1.0')].join('\n\n')
    expect(mergeDuplicateEntries(lockfile)).toContain(header)
  })

  it('leaves the preamble and comments untouched', () => {
    const lockfile = [PREAMBLE, entry('"a@npm:^1.0.0"', 'a@npm:1.0.0')].join('\n\n')
    expect(mergeDuplicateEntries(lockfile).startsWith(PREAMBLE)).toBe(true)
  })

  it('is idempotent', () => {
    const lockfile = [
      PREAMBLE,
      entry('"ms@npm:^2.1.1"', 'ms@npm:2.1.3'),
      entry('"ms@npm:^2.1.3"', 'ms@npm:2.1.3')
    ].join('\n\n')

    const once = mergeDuplicateEntries(lockfile)
    expect(mergeDuplicateEntries(once)).toBe(once)
  })

  it('sorts descriptors and quotes the list as one string', () => {
    expect(joinDescriptors(['b@npm:^2', 'a@npm:^1', 'a@npm:^1'])).toBe('"a@npm:^1, b@npm:^2"')
  })
})
