import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { promises as fs } from 'fs'
import path from 'path'
import os from 'os'
import { detectMobileProject } from '../packages/server/src/mobile-detector'

let dir: string

async function write(rel: string, contents: string): Promise<void> {
  const file = path.join(dir, rel)
  await fs.mkdir(path.dirname(file), { recursive: true })
  await fs.writeFile(file, contents)
}

const pkg = (deps: Record<string, string>): string =>
  JSON.stringify({ name: 'x', dependencies: deps })

beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), 'vorn-mobile-'))
})
afterEach(async () => {
  await fs.rm(dir, { recursive: true, force: true })
})

describe('detectMobileProject', () => {
  it('detects a managed Expo app that has no ios directory', async () => {
    // The case that invalidated the obvious heuristic. Expo's Continuous Native
    // Generation means a real shipping app (Journey: expo 57, RN 0.86) has no
    // `ios/` at all — it is generated by prebuild or built remotely by EAS.
    // Keying detection off `ios/` hides the device button on the very projects
    // that most want it, and nothing reports the omission.
    await write('package.json', pkg({ expo: '~57.0.8', 'react-native': '^0.86.0' }))
    await write('app.config.js', 'module.exports = {}')

    const result = await detectMobileProject(dir)
    expect(result.isMobile).toBe(true)
    expect(result.framework).toBe('expo')
    // No native project locally, so a bare simulator cannot run it from source.
    expect(result.needsDevClient).toBe(true)
  })

  it('does not ask for a dev client when Expo has been prebuilt', async () => {
    await write('package.json', pkg({ expo: '~57.0.8' }))
    await write('ios/App.xcodeproj/project.pbxproj', '')

    expect(await detectMobileProject(dir)).toMatchObject({
      framework: 'expo',
      needsDevClient: false
    })
  })

  it('reports Expo rather than react-native when both are present', async () => {
    // Every Expo app depends on react-native, so first-match-wins on the wrong
    // order would call Journey a bare RN app and silently drop the dev-client
    // warning — the one piece of advice that actually unblocks the person.
    await write('package.json', pkg({ 'react-native': '^0.86.0', expo: '~57.0.8' }))
    expect((await detectMobileProject(dir)).framework).toBe('expo')
  })

  it('detects a bare react-native project', async () => {
    await write('package.json', pkg({ 'react-native': '^0.73.0' }))
    expect(await detectMobileProject(dir)).toMatchObject({
      isMobile: true,
      framework: 'react-native'
    })
  })

  it('detects a Flutter app but not a plain Dart package', async () => {
    await write('pubspec.yaml', 'name: app\ndependencies:\n  flutter:\n    sdk: flutter\n')
    expect((await detectMobileProject(dir)).framework).toBe('flutter')

    const dartDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vorn-dart-'))
    await fs.writeFile(path.join(dartDir, 'pubspec.yaml'), 'name: lib\ndependencies:\n  http: ^1\n')
    // A Dart package has no simulator to drive; offering one is a dead end.
    expect((await detectMobileProject(dartDir)).isMobile).toBe(false)
    await fs.rm(dartDir, { recursive: true, force: true })
  })

  it('detects a native iOS project by its xcodeproj', async () => {
    await write('MyApp.xcodeproj/project.pbxproj', '')
    expect(await detectMobileProject(dir)).toMatchObject({
      isMobile: true,
      framework: 'ios-native'
    })
  })

  it('leaves a web or backend project alone', async () => {
    // The whole point of gating: a device button on a Rails or React repo is
    // noise that suggests the app has misread the project.
    await write('package.json', pkg({ react: '^19.0.0', vite: '^7.0.0' }))
    expect(await detectMobileProject(dir)).toMatchObject({ isMobile: false, framework: null })
  })

  it('survives a malformed package.json instead of throwing', async () => {
    // Mid-edit syntax errors are routine. A throw here would propagate into the
    // sidebar render; the button disappearing on every keystroke would be a
    // baffling symptom to trace back to a comma.
    await write('package.json', '{ "dependencies": { "expo": ')
    await expect(detectMobileProject(dir)).resolves.toMatchObject({ isMobile: false })
  })

  it('returns not-mobile for a missing directory', async () => {
    const gone = await detectMobileProject(path.join(dir, 'nope'))
    expect(gone.isMobile).toBe(false)
  })

  it('finds an Xcode project one level down', async () => {
    // Real shape: fourmis-ios/fourmis/fourmis.xcodeproj. A root-only probe calls
    // this a web project and hides the button on a native iOS app.
    await write('fourmis/fourmis.xcodeproj/project.pbxproj', '')
    expect(await detectMobileProject(dir)).toMatchObject({
      isMobile: true,
      framework: 'ios-native'
    })
  })

  it('ignores xcodeprojs vendored inside node_modules', async () => {
    // Plenty of npm packages ship native iOS code. Descending into node_modules
    // would report every web app that depends on one as a mobile project, and
    // pay a large readdir to reach the wrong answer.
    await write('package.json', pkg({ react: '^19.0.0' }))
    await write('node_modules/RNLib.xcodeproj/project.pbxproj', '')
    expect((await detectMobileProject(dir)).isMobile).toBe(false)
  })
})
