import { promises as fs } from 'fs'
import path from 'path'
import type { MobileProject } from '@vornrun/shared/types'

export type { MobileProject }

const NOT_MOBILE: MobileProject = { isMobile: false, framework: null, needsDevClient: false }

/** Config files that identify an Expo app before any dependency is installed. */
const EXPO_CONFIGS = ['app.json', 'app.config.js', 'app.config.ts', 'app.config.mjs']

/**
 * Directories never worth descending into when looking for an Xcode project.
 *
 * `node_modules` and `Pods` both contain vendored xcodeprojs by the dozen, so
 * scanning them would report a mobile project for any web app that happens to
 * depend on a package shipping native iOS code — and cost a huge readdir to get
 * the wrong answer.
 */
const SKIP_DIRS = new Set(['node_modules', 'Pods', 'build', 'dist', 'vendor', 'Carthage'])

async function readJson(file: string): Promise<Record<string, unknown> | null> {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8')) as Record<string, unknown>
  } catch {
    // Missing, unreadable, or malformed all mean the same thing here: this file
    // cannot testify. A broken package.json must not fail the whole probe, or a
    // syntax error while editing would make the device button vanish.
    return null
  }
}

async function exists(file: string): Promise<boolean> {
  try {
    await fs.access(file)
    return true
  } catch {
    return false
  }
}

/**
 * Decide whether `projectPath` is a mobile project worth offering a device for.
 *
 * Detection keys off declared dependencies and config, never on build output.
 * An `ios/` directory is the tempting signal and the wrong one: Expo's
 * Continuous Native Generation means a real, shipping Expo app commonly has no
 * `ios/` directory at all — it is generated by `expo prebuild` or built
 * remotely. Gating on it hides the button precisely where it is most wanted.
 *
 * Errors resolve to "not mobile" rather than throwing. This decides whether one
 * button is visible; an unreadable directory should cost that button, not the
 * render.
 */
export async function detectMobileProject(projectPath: string): Promise<MobileProject> {
  if (!projectPath) return NOT_MOBILE

  try {
    const pkg = await readJson(path.join(projectPath, 'package.json'))
    if (pkg) {
      const deps = {
        ...((pkg.dependencies as Record<string, string> | undefined) ?? {}),
        ...((pkg.devDependencies as Record<string, string> | undefined) ?? {})
      }
      // Expo is checked first and reported in preference to react-native: every
      // Expo app depends on react-native too, and the Expo answer is the one
      // that carries the dev-client consequence.
      if ('expo' in deps) {
        return {
          isMobile: true,
          framework: 'expo',
          // A bare/prebuilt Expo project has native dirs and builds like RN.
          needsDevClient: !(await exists(path.join(projectPath, 'ios')))
        }
      }
      if ('react-native' in deps) {
        return { isMobile: true, framework: 'react-native', needsDevClient: false }
      }
    }

    // Flutter declares itself in pubspec.yaml; the sdk key distinguishes a
    // Flutter app from a plain Dart package, which has no simulator to drive.
    const pubspec = path.join(projectPath, 'pubspec.yaml')
    if (await exists(pubspec)) {
      const text = await fs.readFile(pubspec, 'utf8').catch(() => '')
      if (/^\s*(sdk:\s*flutter|flutter:)/m.test(text)) {
        return { isMobile: true, framework: 'flutter', needsDevClient: false }
      }
    }

    const entries = await fs.readdir(projectPath).catch(() => [] as string[])
    if (entries.some((e) => e.endsWith('.xcodeproj') || e.endsWith('.xcworkspace'))) {
      return { isMobile: true, framework: 'ios-native', needsDevClient: false }
    }

    // Last, and only as corroboration: an `ios/` directory holding an Xcode
    // project is a prebuilt RN/Expo app whose package.json we could not read.
    if (entries.includes('ios')) {
      const iosEntries = await fs.readdir(path.join(projectPath, 'ios')).catch(() => [] as string[])
      if (iosEntries.some((e) => e.endsWith('.xcodeproj') || e.endsWith('.xcworkspace'))) {
        return { isMobile: true, framework: 'react-native', needsDevClient: false }
      }
    }

    // An Expo config with no installed dependencies yet — a freshly cloned repo
    // before `npm install`, where the button should still appear.
    for (const config of EXPO_CONFIGS) {
      if (entries.includes(config)) {
        return { isMobile: true, framework: 'expo', needsDevClient: !entries.includes('ios') }
      }
    }

    // One level down, and no further. Repos routinely hold the Xcode project in
    // a subdirectory named for the app (fourmis-ios/fourmis/fourmis.xcodeproj),
    // and a root-only probe calls those web projects. The depth cap is what
    // keeps this a bounded readdir of the top level rather than a walk of a tree
    // that might contain node_modules or a Pods directory.
    for (const entry of entries) {
      if (entry.startsWith('.') || SKIP_DIRS.has(entry)) continue
      const nested = await fs.readdir(path.join(projectPath, entry)).catch(() => [] as string[])
      if (nested.some((e) => e.endsWith('.xcodeproj') || e.endsWith('.xcworkspace'))) {
        return { isMobile: true, framework: 'ios-native', needsDevClient: false }
      }
    }

    return NOT_MOBILE
  } catch {
    return NOT_MOBILE
  }
}
